FROM python:3.12-alpine AS builder

# Install Python dependencies
RUN pip install --no-cache-dir \
    requests


FROM python:3.12-alpine
LABEL authors="jdlowel"

# Copy installed packages from builder
COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

# Set working directory
WORKDIR /app

# Copy application code
COPY squishy_coordinator /app/squishy_coordinator/
COPY rest_client /app/rest_client/
COPY integrity_check /app/integrity_check/

# Defaul environment variables configured by coordinator

# Create baseline directory
RUN mkdir -p /baseline

## Start the application using the runnable package
CMD ["python", "-m", "squishy_coordinator"]