FROM joshdlowell/built_images:other
LABEL authors="jdlowel"

# Set working directory
WORKDIR /app

# Copy application code
COPY squishy_coordinator /app/squishy_coordinator/
COPY rest_client /app/rest_client/
COPY integrity_check /app/integrity_check/

# Defaul environment variables configured by coordinator

# Create baseline directory
RUN mkdir -p /baseline

## Start the application using the runnable package
CMD ["python", "-m", "squishy_coordinator"]