FROM joshdlowell/built_images:other
LABEL authors="jdlowel"

# Set working directory
WORKDIR /app

# Copy application code
COPY squishy_integrity /app/squishy_integrity/
COPY rest_client /app/rest_client/
COPY integrity_check /app/integrity_check/

# Set environment variables
ENV REST_API_HOST=squishy_rest_api
ENV REST_API_PORT=5000
ENV BASELINE="/baseline"
ENV DEBUG=False
ENV LOG_LEVEL=INFO

# Create baseline directory
RUN mkdir -p /baseline

## Start the application using the runnable package
CMD ["python", "-m", "squishy_integrity"]