services:
  mysql-squishy-db:
    image: mysql:9.3
    container_name: mysql_squishy_db
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: squishy_db
      MYSQL_USER: your_app_user
      MYSQL_PASSWORD: your_user_password
    volumes:
      - ./squishy_db/init_scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - squishy_db_default
    restart: always

  squishy-rest-api:
    image: squishy-rest-api:v2.0
    container_name: squishy_rest_api
    environment:
      LOCAL_DB_USER: your_app_user
      LOCAL_DB_PASSWORD: your_user_password
      PIPELINE_DB_USER: your_app_user
      PIPELINE_DB_PASSWORD: your_user_password
      API_SECRET_KEY: squishy_key_12345
      SITE_NAME: SIT0
      CORE_NAME: SIT0
    ports:
      - "5000:5000"
    networks:
      - squishy_db_default
    depends_on:
      - mysql-squishy-db
    restart: always

  squishy-integrity:
    image: squishy-integrity:v2.0
    container_name: squishy_integrity
    volumes:
      - /nas/baseline:/baseline
    networks:
      - squishy_db_default
    depends_on:
      - squishy-rest-api
    restart: "no"
    profiles:
      - donotstart

  squishy-coordinator:
    image: squishy-coordinator:v1.0
    container_name: squishy_coordinator
    environment:
      CORE_API_HOST: mysql_squishy_db
      SITE_NAME: SIT0
      CORE_NAME: SIT0
    volumes:
      - /nas/baseline:/baseline
    networks:
      - squishy_db_default
    depends_on:
      - squishy-rest-api
    restart: "no"
    profiles:
      - donotstart

networks:
  squishy_db_default:
    driver: bridge