apiVersion: v1
kind: ConfigMap
metadata:
  name: hashtable-schema
  namespace: default  # Change to real namespace
data:
  schema.sql: |
    CREATE TABLE IF NOT EXISTS hashtable (
        path TEXT NOT NULL,
        hashed_path VARCHAR(64) AS (SHA2(path, 256)) STORED PRIMARY KEY, -- Not case sensitive
        current_hash VARCHAR(40) NOT NULL, -- Not case sensitive
        current_dtg_latest INT UNSIGNED DEFAULT (UNIX_TIMESTAMP()),
        current_dtg_first INT UNSIGNED DEFAULT (`current_dtg_latest`),
        target_hash VARCHAR(40), -- Not case sensitive
        prev_hash VARCHAR(40), -- Not case sensitive
        prev_dtg_latest INT UNSIGNED,
        dirs TEXT,
        files TEXT,
        links TEXT
    );
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logs-schema
  namespace: default  # Change to real namespace
data:
  schema.sql: |
    CREATE TABLE IF NOT EXISTS logs (
        log_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        site_id VARCHAR(5) DEFAULT ('local'), -- Not case sensitive
        log_level ENUM('ERROR', 'STATUS', 'WARNING', 'INFO') DEFAULT ('INFO'), -- Not case sensitive
        timestamp INT UNSIGNED DEFAULT (UNIX_TIMESTAMP()),
        summary_message TEXT NOT NULL,
        detailed_message TEXT
    );
---