services:
  mysql:
    image: mysql:9.3
    container_name: mysql-squishy-db
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: squishy_db
      MYSQL_USER: your_app_user
      MYSQL_PASSWORD: your_user_password
    volumes:
      - ./init_scripts:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data: